import asyncio
import json
import logging
import random
from datetime import datetime
from typing import List, Dict
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import glob
import os
import time
import cv2

# Initialize logger configuration
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("SNP-Backend")

app = FastAPI(
    title="SwachNikaasPravah (SNP) App Engine",
    description="Centralized Stream Analytics & Risk Fusion Pipeline",
    version="1.0.0"
)

# Enable Cross-Origin Resource Sharing (CORS) for smooth React client communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this to your React origin (e.g., ["http://localhost:5173"])
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Try importing Ultralytics for active YOLO inference execution
try:
    from ultralytics import YOLO
    # Fallback to standard base nano weights if fine-tuned weights are not yet generated
    # Fixed to match the exact double-nested path generated by the training run
    MODEL_PATH = "./runs/detect/runs/detect/snp_runs/drain_premium_model/weights/best.pt"
    mmodel = YOLO(MODEL_PATH) if os.path.exists(MODEL_PATH) else YOLO("yolov8n.pt")
    HAS_YOLO = True
    logger.info(f"YOLO engine initialized successfully using active framework pipeline.")
except ImportError:
    HAS_YOLO = False
    logger.warning("Ultralytics library missing or CUDA mapping error. Operating on pure high-fidelity simulation engine.")

# =====================================================================
# SYSTEM STATIC MASTER DATABASE MOCK OBJECTS
# =====================================================================
DRAIN_ASSETS = {
    "MUM-WOR-018": {"id": "MUM-WOR-018", "name": "Worli Sea Face Box", "city": "Mumbai", "type": "Box Culvert", "lat": 19.0025, "lng": 72.8152, "topo": 0.93, "uptime": 97.2},
    "HYD-MDP-003": {"id": "HYD-MDP-003", "name": "Madhapur HITEC Underpass", "city": "Hyderabad", "type": "Box Culvert", "lat": 17.4435, "lng": 78.3772, "topo": 0.91, "uptime": 97.7},
    "MUM-BKC-002": {"id": "MUM-BKC-002", "name": "BKC Connector Drain", "city": "Mumbai", "type": "Box Culvert", "lat": 19.0601, "lng": 72.8644, "topo": 0.88, "uptime": 98.3},
    "HYD-GCB-014": {"id": "HYD-GCB-014", "name": "Gachibowli Jn. Main Outfall", "city": "Hyderabad", "type": "Stormwater", "lat": 17.4401, "lng": 78.3489, "topo": 0.82, "uptime": 99.4},
    "HYD-KHJ-009": {"id": "HYD-KHJ-009", "name": "Khairatabad Flyover", "city": "Hyderabad", "type": "Combined", "lat": 17.4123, "lng": 78.4578, "topo": 0.75, "uptime": 96.4},
    "HYD-KKD-007": {"id": "HYD-KKD-007", "name": "Kukatpally Y-Junction", "city": "Hyderabad", "type": "Combined", "lat": 17.4842, "lng": 78.4089, "topo": 0.71, "uptime": 98.1}
}

# In-memory runtime tracking system states
current_states = {drain_id: {"blockage": random.randint(15, 45), "rain_6h": random.randint(5, 20), "status": "NORMAL", "risk_score": 0.0} for drain_id in DRAIN_ASSETS}
active_tickets = {}

# =====================================================================
# REUSABLE PIPELINE ALGORITHMS
# =====================================================================
def calculate_risk_fusion_index(ab: float, rf: float, vt: float) -> float:
    """
    Computes the Multi-Signal Threat Priority Matrix Score.
    Equation: RI = (0.5 * Ab) + (0.3 * Rf) + (0.2 * Vt)
    Normalized inputs mapping:
      - ab: Blockage Ratio (Percentage 0 - 100)
      - rf: Rainfall prediction forecast mm (Mapped up to a 100mm upper bound threshold)
      - vt: Topological asset vulnerability multiplier (Scale 0.0 - 1.0)
    """
    normalized_rain = min(rf, 100.0)  # Caps max rain factor at 100mm depth normalization
    risk_score = (0.5 * ab) + (0.3 * normalized_rain) + (0.2 * (vt * 100))
    return round(risk_score, 1)

# =====================================================================
# ACTIVE WEBSOCKET MANAGER CONTEXT
# =====================================================================
class ConnectionManager:
    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        logger.info(f"Active client connection added to streaming websocket pool. Total: {len(self.active_connections)}")

    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)
        logger.info(f"Client disconnected from WebSocket pool. Total remaining: {len(self.active_connections)}")

    async def broadcast_payload(self, message: dict):
        for connection in self.active_connections:
            try:
                await connection.send_text(json.dumps(message))
            except Exception:
                # Catch dead socket exceptions cleanly
                pass

manager = ConnectionManager()

# =====================================================================
# FASTAPI INPUT CONTRACT SCHEMAS (Pydantic Models)
# =====================================================================
class DispatchRequest(BaseModel):
    ticket_id: str
    crew_id: str

class DismissRequest(BaseModel):
    drain_id: str

# =====================================================================
# AUTOMATED PIPELINE PROCESS SIMULATION LOOP
# =====================================================================
async def background_telemetry_loop():
    """Simulates persistent frame capture ingestion sequence over open cameras."""
    while True:
        await asyncio.sleep(4.0)  # Stream frequency updates every 4 seconds to dashboard
        if not manager.active_connections:
            continue

        # Select a random asset to organically simulate dynamic threat fluctuations
        target_id = random.choice(list(DRAIN_ASSETS.keys()))
        asset = DRAIN_ASSETS[target_id]
        
        # Keep values normal if not escalated via storm simulation overrides
        if current_states[target_id]["status"] != "CRITICAL":
            current_states[target_id]["blockage"] = min(100, max(0, current_states[target_id]["blockage"] + random.randint(-5, 5)))
            current_states[target_id]["rain_6h"] = min(100, max(0, current_states[target_id]["rain_6h"] + random.randint(-2, 2)))
        
        # Execute the Multi-Signal mathematical score evaluation block
        ri = calculate_risk_fusion_index(
            current_states[target_id]["blockage"],
            current_states[target_id]["rain_6h"],
            asset["topo"]
        )
        current_states[target_id]["risk_score"] = ri

        # Evaluate risk category tiers
        if ri >= 70.0 and current_states[target_id]["status"] != "DISPATCHED":
            current_states[target_id]["status"] = "CRITICAL"
        elif ri >= 45.0 and current_states[target_id]["status"] != "DISPATCHED":
            current_states[target_id]["status"] = "WARNING"
        elif current_states[target_id]["status"] != "DISPATCHED":
            current_states[target_id]["status"] = "NORMAL"

        # Construct payload message packet mapping back to schema specifications
        payload = {
            "event": "TELEMETRY_UPDATE",
            "data": {
                "drain_id": target_id,
                "blockage_ratio": current_states[target_id]["blockage"],
                "incoming_rain_mm": current_states[target_id]["rain_6h"],
                "risk_score": current_states[target_id]["risk_score"],
                "status": current_states[target_id]["status"],
                "timestamp": datetime.utcnow().isoformat() + "Z"
            }
        }
        await manager.broadcast_payload(payload)

@app.on_event("startup")
async def startup_event_wrapper():
    # Spin up our automated simulation worker loop safely as an asynchronous task
    asyncio.create_task(background_telemetry_loop())

# =====================================================================
# REST CHANNELS & ROUTING ENDPOINTS
# =====================================================================
@app.get("/api/v1/drains")
async def get_all_registered_assets():
    """Exposes current statuses and properties of all registered infrastructure assets."""
    combined_response = []
    for drain_id, details in DRAIN_ASSETS.items():
        combined_response.append({**details, **current_states[drain_id]})
    return combined_response

@app.post("/api/v1/simulate-storm")
async def trigger_simulated_flash_flood_scenario():
    """Forces all system components into elevated alarm thresholds instantly."""
    logger.info("CRITICAL EVENT INJECTION: Simulating severe localized downpour scenario across system boundaries.")
    
    for drain_id in DRAIN_ASSETS:
        # Mutate the in-memory array properties to force severe clogging triggers
        current_states[drain_id]["blockage"] = random.randint(72, 95)
        current_states[drain_id]["rain_6h"] = random.randint(55, 88)
        current_states[drain_id]["status"] = "CRITICAL"
        current_states[drain_id]["risk_score"] = calculate_risk_fusion_index(
            current_states[drain_id]["blockage"],
            current_states[drain_id]["rain_6h"],
            DRAIN_ASSETS[drain_id]["topo"]
        )
        
        # Build immediate WebSocket transmission packet
        alert_payload = {
            "event": "BLOCKAGE_ALERT",
            "data": {
                "drain_id": drain_id,
                "blockage_ratio": current_states[drain_id]["blockage"],
                "incoming_rain_mm": current_states[drain_id]["rain_6h"],
                "risk_score": current_states[drain_id]["risk_score"],
                "status": "CRITICAL",
                "timestamp": datetime.utcnow().isoformat() + "Z"
            }
        }
        await manager.broadcast_payload(alert_payload)
        
    return {"status": "success", "message": "Simulated storm event successfully pushed over WebSocket gateway pipelines."}

@app.post("/api/v1/dispatch")
async def process_crew_mobilization(payload: DispatchRequest):
    """Processes verification states and transitions active structural alerts to dispatch updates."""
    logger.info(f"Transitioning Ticket Context: Ticket {payload.ticket_id} mapped directly to Field Unit: {payload.crew_id}")
    return {
        "status": "success", 
        "message": f"Mobilization order verified. Routing directives sent to {payload.crew_id}.",
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }

@app.post("/api/v1/dismiss")
async def process_alert_dismissal(payload: DismissRequest):
    """Clears localized transient alert anomalies back down to secure monitoring levels."""
    if payload.drain_id not in current_states:
        raise HTTPException(status_code=404, detail="Drain target reference index not found inside database schema.")
        
    current_states[payload.drain_id]["status"] = "NORMAL"
    current_states[payload.drain_id]["blockage"] = random.randint(10, 25)
    
    # Push immediate structural clearance synchronization back out to client screens
    clearance_payload = {
        "event": "ALERT_DISMISSED",
        "data": {"drain_id": payload.drain_id, "status": "NORMAL", "blockage_ratio": current_states[payload.drain_id]["blockage"]}
    }
    await manager.broadcast_payload(clearance_payload)
    return {"status": "success", "message": f"Asset {payload.drain_id} cleared and reset to normal monitoring parameters."}

# =====================================================================
# WEBSOCKET SUBSCRIPTION CHANNEL ROUTER
# =====================================================================
@app.websocket("/api/v1/stream/alerts")
async def websocket_stream_endpoint(websocket: WebSocket):
    """Real-time network pipe enabling direct asynchronous server pushes to Lovable client views."""
    await manager.connect(websocket)
    try:
        while True:
            # Maintain active persistent connection state frame
            data = await websocket.receive_text()
            # Handle incoming ping/pong confirmation arrays cleanly if submitted by client hooks
            logger.info(f"WebSocket input message captured from client endpoint: {data}")
    except WebSocketDisconnect:
        manager.disconnect(websocket)


def generate_video_frames(render_inference: bool = False):
    """
    Scans the downloaded validation dataset directory and streams images 
    sequentially to simulate a live, frame-snapping ICCC camera feed.
    """
    # Dynamically locate your validation image directory
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # backend/
    image_dir = os.path.join(base_dir, "ml_training", "valid", "images")
    
    # Grab all valid image assets inside the dataset split
    image_extensions = ["*.jpg", "*.jpeg", "*.png", "*.JPG"]
    image_paths = []
    for ext in image_extensions:
        image_paths.extend(glob.glob(os.path.join(image_dir, ext)))
        
    if not image_paths:
        logger.error(f"No validation source frames found at target path: {image_dir}")
        return

    # Sort files to ensure clean, consistent streaming playback frames
    image_paths.sort()

    while True:
        for img_path in image_paths:
            frame = cv2.imread(img_path)
            if frame is None:
                continue

            # Resize to look clean inside your layout viewports
            frame = cv2.resize(frame, (640, 480))

            # If rendering the analytical view, apply your newly trained weights
            if render_inference and HAS_YOLO:
                results = model(frame, conf=0.25, verbose=False)[0]
                frame = results.plot()
            
            # Encode frame to JPEG format
            ret, buffer = cv2.imencode('.jpg', frame)
            if not ret:
                continue
                
            frame_bytes = buffer.tobytes()
            
            # Yield frame chunk over HTTP gateway boundaries
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')
            
            # Control feed speed: 1.5 seconds per frame simulates low-bandwidth CCTV perfectly
            time.sleep(1.5)