artifact_location: /home/akhil/DrainageAi/runs/mlflow/857362172808515589
creation_time: 1782025571783
experiment_id: '857362172808515589'
last_update_time: 1782025571783
lifecycle_stage: active
name: snp_runs
trace_location: null
workspace: default
